ROOT_PATH: "/mnt/home/jdelker"    # The root path prefixed to all other paths in this file
EOS_PATH: "/mnt/home/jdelker/test_osnap_project/SFHo.h5"    # Path to the Equation of State HDF5 database file
STIR_RESULTS_PATH: "/mnt/research/SNAPhU/STIR/run_sukhbold/run_14may19_a1.25/run_12.0/stir2_14may19_s12.0_alpha1.25.dat"
STIR_CHECKPOINT_FOLDER: "/mnt/research/SNAPhU/STIR/run_sukhbold/run_14may19_a1.25/run_12.0/output/"